import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="604897553948-kkjr55fpo7bei4bfa4b7b319vrllrg61.apps.googleusercontent.com">
          {children}
        </GoogleOAuthProvider>
        ;
      </body>
    </html>
  );
}
